The following code ensures that Google CoLab is running the correct version of TensorFlow.

try:
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False
Part 10.3: Text Generation with LSTM
Recurrent neural networks are also known for their ability to generate text. As a result, the output of the neural network can be free-form text. In this section, we will see how to train an LSTM can on a textual document, such as classic literature, and learn to output new text that appears to be of the same form as the training material. If you train your LSTM on Shakespeare, it will learn to crank out new prose similar to what Shakespeare had written.

Don't get your hopes up. You are not going to teach your deep neural network to write the next Pulitzer Prize for Fiction. The prose generated by your neural network will be nonsensical. However, it will usually be nearly grammatically and of a similar style as the source training documents.

A neural network generating nonsensical text based on literature may not seem useful at first glance. However, this technology gets so much interest because it forms the foundation for many more advanced technologies. The fact that the LSTM will typically learn human grammar from the source document opens a wide range of possibilities. You can use similar technology to complete sentences when a user is entering text. Simply the ability to output free-form text becomes the foundation of many other technologies. In the next part, we will use this technique to create a neural network that can write captions for images to describe what is going on in the picture.

Additional Information
The following are some of the articles that I found useful in putting this section together.

The Unreasonable Effectiveness of Recurrent Neural Networks
Keras LSTM Generation Example
Character-Level Text Generation
There are several different approaches to teaching a neural network to output free-form text. The most basic question is if you wish the neural network to learn at the word or character level. In many ways, learning at the character level is the more interesting of the two. The LSTM is learning to construct its own words without even being shown what a word is. We will begin with character-level text generation. In the next module, we will see how we can use nearly the same technique to operate at the word level. We will implement word-level automatic captioning in the next module.

We begin by importing the needed Python packages and defining the sequence length, named maxlen. Time-series neural networks always accept their input as a fixed-length array. Because you might not use all of the sequence elements, it is common to fill extra elements with zeros. You will divide the text into sequences of this length, and the neural network will train to predict what comes after this sequence.

from tensorflow.keras.callbacks import LambdaCallback
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.utils import get_file
import numpy as np
import random
import sys
import io
import requests
import re
For this simple example, we will train the neural network on the classic children's book Treasure Island. We begin by loading this text into a Python string and displaying the first 1,000 characters.

r = requests.get("https://data.heatonresearch.com/data/t81-558/text/"\
                 "treasure_island.txt")
raw_text = r.text
print(raw_text[0:1000])
ï»¿The Project Gutenberg EBook of Treasure Island, by Robert Louis Stevenson

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.net


Title: Treasure Island

Author: Robert Louis Stevenson

Illustrator: Milo Winter

Release Date: January 12, 2009 [EBook #27780]

Language: English


*** START OF THIS PROJECT GUTENBERG EBOOK TREASURE ISLAND ***




Produced by Juliet Sutherland, Stephen Blundell and the
Online Distributed Proofreading Team at http://www.pgdp.net









 THE ILLUSTRATED CHILDREN'S LIBRARY


         _Treasure Island_

       Robert Louis Stevenson

          _Illustrated by_
            Milo Winter


           [Illustration]


           GRAMERCY BOOKS
              NEW YORK




 Foreword copyright Â© 1986 by Random House V
We will extract all unique characters from the text and sort them. This technique allows us to assign a unique ID to each character. Because we sorted the characters, these IDs should remain the same. If we add new characters to the original text, then the IDs would change. We build two dictionaries. The first char2idx is used to convert a character into its ID. The second idx2char converts an ID back into its character.

processed_text = raw_text.lower()
processed_text = re.sub(r'[^\x00-\x7f]',r'', processed_text) 
print('corpus length:', len(processed_text))

chars = sorted(list(set(processed_text)))
print('total chars:', len(chars))
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))
corpus length: 397400
total chars: 60
We are now ready to build the actual sequences. Just like previous neural networks, there will be an  and . However, for the LSTM,  and  will both be sequences. The  input will specify the sequences where  are the expected output. The following code generates all possible sequences.

# cut the text in semi-redundant sequences of maxlen characters
maxlen = 40
step = 3
sentences = []
next_chars = []
for i in range(0, len(processed_text) - maxlen, step):
    sentences.append(processed_text[i: i + maxlen])
    next_chars.append(processed_text[i + maxlen])
print('nb sequences:', len(sentences))
nb sequences: 132454
sentences
['the project gutenberg ebook of treasure ',
 ' project gutenberg ebook of treasure isl',
 'oject gutenberg ebook of treasure island',
 'ct gutenberg ebook of treasure island, b',
 'gutenberg ebook of treasure island, by r',
 'enberg ebook of treasure island, by robe',
 'erg ebook of treasure island, by robert ',
 ' ebook of treasure island, by robert lou',
 'ook of treasure island, by robert louis ',
 ' of treasure island, by robert louis ste',
 ' treasure island, by robert louis steven',
 'easure island, by robert louis stevenson',
 'ure island, by robert louis stevenson\r\n\r',
 ' island, by robert louis stevenson\r\n\r\nth',
 'land, by robert louis stevenson\r\n\r\nthis ',
 'd, by robert louis stevenson\r\n\r\nthis ebo',
 'by robert louis stevenson\r\n\r\nthis ebook ',
 'robert louis stevenson\r\n\r\nthis ebook is ',
 'ert louis stevenson\r\n\r\nthis ebook is for',
 ' louis stevenson\r\n\r\nthis ebook is for th',
 'uis stevenson\r\n\r\nthis ebook is for the u',
 ' stevenson\r\n\r\nthis ebook is for the use ',
 'evenson\r\n\r\nthis ebook is for the use of ',
 'nson\r\n\r\nthis ebook is for the use of any',
 'n\r\n\r\nthis ebook is for the use of anyone',
 '\r\nthis ebook is for the use of anyone an',
 'his ebook is for the use of anyone anywh',
 ' ebook is for the use of anyone anywhere',
 'ook is for the use of anyone anywhere at',
 ' is for the use of anyone anywhere at no',
 ' for the use of anyone anywhere at no co',
 'r the use of anyone anywhere at no cost ',
 'he use of anyone anywhere at no cost and',
 'use of anyone anywhere at no cost and wi',
 ' of anyone anywhere at no cost and with\r',
 ' anyone anywhere at no cost and with\r\nal',
 'yone anywhere at no cost and with\r\nalmos',
 'e anywhere at no cost and with\r\nalmost n',
 'nywhere at no cost and with\r\nalmost no r',
 'here at no cost and with\r\nalmost no rest',
 'e at no cost and with\r\nalmost no restric',
 't no cost and with\r\nalmost no restrictio',
 'o cost and with\r\nalmost no restrictions ',
 'ost and with\r\nalmost no restrictions wha',
 ' and with\r\nalmost no restrictions whatso',
 'd with\r\nalmost no restrictions whatsoeve',
 'ith\r\nalmost no restrictions whatsoever. ',
 '\r\nalmost no restrictions whatsoever.  yo',
 'lmost no restrictions whatsoever.  you m',
 'st no restrictions whatsoever.  you may ',
 'no restrictions whatsoever.  you may cop',
 'restrictions whatsoever.  you may copy i',
 'trictions whatsoever.  you may copy it, ',
 'ctions whatsoever.  you may copy it, giv',
 'ons whatsoever.  you may copy it, give i',
 ' whatsoever.  you may copy it, give it a',
 'atsoever.  you may copy it, give it away',
 'oever.  you may copy it, give it away or',
 'er.  you may copy it, give it away or\r\nr',
 '  you may copy it, give it away or\r\nre-u',
 'ou may copy it, give it away or\r\nre-use ',
 'may copy it, give it away or\r\nre-use it ',
 ' copy it, give it away or\r\nre-use it und',
 'py it, give it away or\r\nre-use it under ',
 'it, give it away or\r\nre-use it under the',
 ' give it away or\r\nre-use it under the te',
 've it away or\r\nre-use it under the terms',
 'it away or\r\nre-use it under the terms of',
 'away or\r\nre-use it under the terms of th',
 'y or\r\nre-use it under the terms of the p',
 'r\r\nre-use it under the terms of the proj',
 're-use it under the terms of the project',
 'use it under the terms of the project gu',
 ' it under the terms of the project guten',
 ' under the terms of the project gutenber',
 'der the terms of the project gutenberg l',
 ' the terms of the project gutenberg lice',
 'e terms of the project gutenberg license',
 'erms of the project gutenberg license in',
 's of the project gutenberg license inclu',
 'f the project gutenberg license included',
 'he project gutenberg license included\r\nw',
 'project gutenberg license included\r\nwith',
 'ject gutenberg license included\r\nwith th',
 't gutenberg license included\r\nwith this ',
 'utenberg license included\r\nwith this ebo',
 'nberg license included\r\nwith this ebook ',
 'rg license included\r\nwith this ebook or ',
 'license included\r\nwith this ebook or onl',
 'ense included\r\nwith this ebook or online',
 'e included\r\nwith this ebook or online at',
 'ncluded\r\nwith this ebook or online at ww',
 'uded\r\nwith this ebook or online at www.g',
 'd\r\nwith this ebook or online at www.gute',
 'with this ebook or online at www.gutenbe',
 'h this ebook or online at www.gutenberg.',
 'his ebook or online at www.gutenberg.net',
 ' ebook or online at www.gutenberg.net\r\n\r',
 'ook or online at www.gutenberg.net\r\n\r\n\r\n',
 ' or online at www.gutenberg.net\r\n\r\n\r\ntit',
 ' online at www.gutenberg.net\r\n\r\n\r\ntitle:',
 'line at www.gutenberg.net\r\n\r\n\r\ntitle: tr',
 'e at www.gutenberg.net\r\n\r\n\r\ntitle: treas',
 't www.gutenberg.net\r\n\r\n\r\ntitle: treasure',
 'ww.gutenberg.net\r\n\r\n\r\ntitle: treasure is',
 'gutenberg.net\r\n\r\n\r\ntitle: treasure islan',
 'enberg.net\r\n\r\n\r\ntitle: treasure island\r\n',
 'erg.net\r\n\r\n\r\ntitle: treasure island\r\n\r\na',
 '.net\r\n\r\n\r\ntitle: treasure island\r\n\r\nauth',
 't\r\n\r\n\r\ntitle: treasure island\r\n\r\nauthor:',
 '\r\n\r\ntitle: treasure island\r\n\r\nauthor: ro',
 '\ntitle: treasure island\r\n\r\nauthor: rober',
 'tle: treasure island\r\n\r\nauthor: robert l',
 ': treasure island\r\n\r\nauthor: robert loui',
 'reasure island\r\n\r\nauthor: robert louis s',
 'sure island\r\n\r\nauthor: robert louis stev',
 'e island\r\n\r\nauthor: robert louis stevens',
 'sland\r\n\r\nauthor: robert louis stevenson\r',
 'nd\r\n\r\nauthor: robert louis stevenson\r\n\r\n',
 '\n\r\nauthor: robert louis stevenson\r\n\r\nill',
 'author: robert louis stevenson\r\n\r\nillust',
 'hor: robert louis stevenson\r\n\r\nillustrat',
 ': robert louis stevenson\r\n\r\nillustrator:',
 'obert louis stevenson\r\n\r\nillustrator: mi',
 'rt louis stevenson\r\n\r\nillustrator: milo ',
 'louis stevenson\r\n\r\nillustrator: milo win',
 'is stevenson\r\n\r\nillustrator: milo winter',
 'stevenson\r\n\r\nillustrator: milo winter\r\n\r',
 'venson\r\n\r\nillustrator: milo winter\r\n\r\nre',
 'son\r\n\r\nillustrator: milo winter\r\n\r\nrelea',
 '\r\n\r\nillustrator: milo winter\r\n\r\nrelease ',
 '\nillustrator: milo winter\r\n\r\nrelease dat',
 'lustrator: milo winter\r\n\r\nrelease date: ',
 'trator: milo winter\r\n\r\nrelease date: jan',
 'tor: milo winter\r\n\r\nrelease date: januar',
 ': milo winter\r\n\r\nrelease date: january 1',
 'ilo winter\r\n\r\nrelease date: january 12, ',
 ' winter\r\n\r\nrelease date: january 12, 200',
 'nter\r\n\r\nrelease date: january 12, 2009 [',
 'r\r\n\r\nrelease date: january 12, 2009 [ebo',
 '\r\nrelease date: january 12, 2009 [ebook ',
 'elease date: january 12, 2009 [ebook #27',
 'ase date: january 12, 2009 [ebook #27780',
 ' date: january 12, 2009 [ebook #27780]\r\n',
 'te: january 12, 2009 [ebook #27780]\r\n\r\nl',
 ' january 12, 2009 [ebook #27780]\r\n\r\nlang',
 'nuary 12, 2009 [ebook #27780]\r\n\r\nlanguag',
 'ry 12, 2009 [ebook #27780]\r\n\r\nlanguage: ',
 '12, 2009 [ebook #27780]\r\n\r\nlanguage: eng',
 ' 2009 [ebook #27780]\r\n\r\nlanguage: englis',
 '09 [ebook #27780]\r\n\r\nlanguage: english\r\n',
 '[ebook #27780]\r\n\r\nlanguage: english\r\n\r\n\r',
 'ook #27780]\r\n\r\nlanguage: english\r\n\r\n\r\n**',
 ' #27780]\r\n\r\nlanguage: english\r\n\r\n\r\n*** s',
 '7780]\r\n\r\nlanguage: english\r\n\r\n\r\n*** star',
 '0]\r\n\r\nlanguage: english\r\n\r\n\r\n*** start o',
 '\n\r\nlanguage: english\r\n\r\n\r\n*** start of t',
 'language: english\r\n\r\n\r\n*** start of this',
 'guage: english\r\n\r\n\r\n*** start of this pr',
 'ge: english\r\n\r\n\r\n*** start of this proje',
 ' english\r\n\r\n\r\n*** start of this project ',
 'glish\r\n\r\n\r\n*** start of this project gut',
 'sh\r\n\r\n\r\n*** start of this project gutenb',
 '\n\r\n\r\n*** start of this project gutenberg',
 '\r\n*** start of this project gutenberg eb',
 '** start of this project gutenberg ebook',
 'start of this project gutenberg ebook tr',
 'rt of this project gutenberg ebook treas',
 'of this project gutenberg ebook treasure',
 'this project gutenberg ebook treasure is',
 's project gutenberg ebook treasure islan',
 'roject gutenberg ebook treasure island *',
 'ect gutenberg ebook treasure island ***\r',
 ' gutenberg ebook treasure island ***\r\n\r\n',
 'tenberg ebook treasure island ***\r\n\r\n\r\n\r',
 'berg ebook treasure island ***\r\n\r\n\r\n\r\n\r\n',
 'g ebook treasure island ***\r\n\r\n\r\n\r\n\r\npro',
 'book treasure island ***\r\n\r\n\r\n\r\n\r\nproduc',
 'k treasure island ***\r\n\r\n\r\n\r\n\r\nproduced ',
 'reasure island ***\r\n\r\n\r\n\r\n\r\nproduced by ',
 'sure island ***\r\n\r\n\r\n\r\n\r\nproduced by jul',
 'e island ***\r\n\r\n\r\n\r\n\r\nproduced by juliet',
 'sland ***\r\n\r\n\r\n\r\n\r\nproduced by juliet su',
 'nd ***\r\n\r\n\r\n\r\n\r\nproduced by juliet suthe',
 '***\r\n\r\n\r\n\r\n\r\nproduced by juliet sutherla',
 '\r\n\r\n\r\n\r\n\r\nproduced by juliet sutherland,',
 '\n\r\n\r\n\r\nproduced by juliet sutherland, st',
 '\r\n\r\nproduced by juliet sutherland, steph',
 '\nproduced by juliet sutherland, stephen ',
 'oduced by juliet sutherland, stephen blu',
 'ced by juliet sutherland, stephen blunde',
 ' by juliet sutherland, stephen blundell ',
 ' juliet sutherland, stephen blundell and',
 'liet sutherland, stephen blundell and th',
 't sutherland, stephen blundell and the\r\n',
 'utherland, stephen blundell and the\r\nonl',
 'erland, stephen blundell and the\r\nonline',
 'and, stephen blundell and the\r\nonline di',
 ', stephen blundell and the\r\nonline distr',
 'tephen blundell and the\r\nonline distribu',
 'hen blundell and the\r\nonline distributed',
 ' blundell and the\r\nonline distributed pr',
 'undell and the\r\nonline distributed proof',
 'ell and the\r\nonline distributed proofrea',
 ' and the\r\nonline distributed proofreadin',
 'd the\r\nonline distributed proofreading t',
 'he\r\nonline distributed proofreading team',
 '\nonline distributed proofreading team at',
 'line distributed proofreading team at ht',
 'e distributed proofreading team at http:',
 'istributed proofreading team at http://w',
 'ributed proofreading team at http://www.',
 'uted proofreading team at http://www.pgd',
 'd proofreading team at http://www.pgdp.n',
 'roofreading team at http://www.pgdp.net\r',
 'freading team at http://www.pgdp.net\r\n\r\n',
 'ading team at http://www.pgdp.net\r\n\r\n\r\n\r',
 'ng team at http://www.pgdp.net\r\n\r\n\r\n\r\n\r\n',
 'team at http://www.pgdp.net\r\n\r\n\r\n\r\n\r\n\r\n\r',
 'm at http://www.pgdp.net\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n',
 't http://www.pgdp.net\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r',
 'ttp://www.pgdp.net\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n t',
 '://www.pgdp.net\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n the ',
 'www.pgdp.net\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n the ill',
 '.pgdp.net\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n the illust',
 'dp.net\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n the illustrat',
 'net\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n the illustrated ',
 '\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n the illustrated chi',
 '\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n the illustrated childr',
 "\r\n\r\n\r\n\r\n\r\n\r\n\r\n the illustrated children'",
 "\n\r\n\r\n\r\n\r\n\r\n the illustrated children's l",
 "\r\n\r\n\r\n\r\n the illustrated children's libr",
 "\n\r\n\r\n the illustrated children's library",
 "\r\n the illustrated children's library\r\n\r",
 "the illustrated children's library\r\n\r\n\r\n",
 " illustrated children's library\r\n\r\n\r\n   ",
 "lustrated children's library\r\n\r\n\r\n      ",
 "trated children's library\r\n\r\n\r\n         ",
 "ted children's library\r\n\r\n\r\n         _tr",
 " children's library\r\n\r\n\r\n         _treas",
 "ildren's library\r\n\r\n\r\n         _treasure",
 "ren's library\r\n\r\n\r\n         _treasure is",
 "'s library\r\n\r\n\r\n         _treasure islan",
 'library\r\n\r\n\r\n         _treasure island_\r',
 'rary\r\n\r\n\r\n         _treasure island_\r\n\r\n',
 'y\r\n\r\n\r\n         _treasure island_\r\n\r\n   ',
 '\r\n\r\n         _treasure island_\r\n\r\n      ',
 '\n         _treasure island_\r\n\r\n       ro',
 '       _treasure island_\r\n\r\n       rober',
 '    _treasure island_\r\n\r\n       robert l',
 ' _treasure island_\r\n\r\n       robert loui',
 'reasure island_\r\n\r\n       robert louis s',
 'sure island_\r\n\r\n       robert louis stev',
 'e island_\r\n\r\n       robert louis stevens',
 'sland_\r\n\r\n       robert louis stevenson\r',
 'nd_\r\n\r\n       robert louis stevenson\r\n\r\n',
 '\r\n\r\n       robert louis stevenson\r\n\r\n   ',
 '\n       robert louis stevenson\r\n\r\n      ',
 '     robert louis stevenson\r\n\r\n         ',
 '  robert louis stevenson\r\n\r\n          _i',
 'obert louis stevenson\r\n\r\n          _illu',
 'rt louis stevenson\r\n\r\n          _illustr',
 'louis stevenson\r\n\r\n          _illustrate',
 'is stevenson\r\n\r\n          _illustrated b',
 'stevenson\r\n\r\n          _illustrated by_\r',
 'venson\r\n\r\n          _illustrated by_\r\n  ',
 'son\r\n\r\n          _illustrated by_\r\n     ',
 '\r\n\r\n          _illustrated by_\r\n        ',
 '\n          _illustrated by_\r\n           ',
 '        _illustrated by_\r\n            mi',
 '     _illustrated by_\r\n            milo ',
 '  _illustrated by_\r\n            milo win',
 'illustrated by_\r\n            milo winter',
 'ustrated by_\r\n            milo winter\r\n\r',
 'rated by_\r\n            milo winter\r\n\r\n\r\n',
 'ed by_\r\n            milo winter\r\n\r\n\r\n   ',
 'by_\r\n            milo winter\r\n\r\n\r\n      ',
 '\r\n            milo winter\r\n\r\n\r\n         ',
 '           milo winter\r\n\r\n\r\n           [',
 '        milo winter\r\n\r\n\r\n           [ill',
 '     milo winter\r\n\r\n\r\n           [illust',
 '  milo winter\r\n\r\n\r\n           [illustrat',
 'ilo winter\r\n\r\n\r\n           [illustration',
 ' winter\r\n\r\n\r\n           [illustration]\r\n',
 'nter\r\n\r\n\r\n           [illustration]\r\n\r\n\r',
 'r\r\n\r\n\r\n           [illustration]\r\n\r\n\r\n  ',
 '\r\n\r\n           [illustration]\r\n\r\n\r\n     ',
 '\n           [illustration]\r\n\r\n\r\n        ',
 '         [illustration]\r\n\r\n\r\n           ',
 '      [illustration]\r\n\r\n\r\n           gra',
 '   [illustration]\r\n\r\n\r\n           gramer',
 '[illustration]\r\n\r\n\r\n           gramercy ',
 'lustration]\r\n\r\n\r\n           gramercy boo',
 'tration]\r\n\r\n\r\n           gramercy books\r',
 'tion]\r\n\r\n\r\n           gramercy books\r\n  ',
 'n]\r\n\r\n\r\n           gramercy books\r\n     ',
 '\n\r\n\r\n           gramercy books\r\n        ',
 '\r\n           gramercy books\r\n           ',
 '          gramercy books\r\n              ',
 '       gramercy books\r\n              new',
 '    gramercy books\r\n              new yo',
 ' gramercy books\r\n              new york\r',
 'amercy books\r\n              new york\r\n\r\n',
 'rcy books\r\n              new york\r\n\r\n\r\n\r',
 ' books\r\n              new york\r\n\r\n\r\n\r\n\r\n',
 'oks\r\n              new york\r\n\r\n\r\n\r\n\r\n fo',
 '\r\n              new york\r\n\r\n\r\n\r\n\r\n forew',
 '             new york\r\n\r\n\r\n\r\n\r\n foreword',
 '          new york\r\n\r\n\r\n\r\n\r\n foreword co',
 '       new york\r\n\r\n\r\n\r\n\r\n foreword copyr',
 '    new york\r\n\r\n\r\n\r\n\r\n foreword copyrigh',
 ' new york\r\n\r\n\r\n\r\n\r\n foreword copyright  ',
 'w york\r\n\r\n\r\n\r\n\r\n foreword copyright  198',
 'ork\r\n\r\n\r\n\r\n\r\n foreword copyright  1986 b',
 '\r\n\r\n\r\n\r\n\r\n foreword copyright  1986 by r',
 '\n\r\n\r\n\r\n foreword copyright  1986 by rand',
 '\r\n\r\n foreword copyright  1986 by random ',
 '\n foreword copyright  1986 by random hou',
 'oreword copyright  1986 by random house ',
 'word copyright  1986 by random house val',
 'd copyright  1986 by random house value ',
 'opyright  1986 by random house value pub',
 'right  1986 by random house value publis',
 'ht  1986 by random house value publishin',
 ' 1986 by random house value publishing\r\n',
 '86 by random house value publishing\r\n co',
 'by random house value publishing\r\n color',
 'random house value publishing\r\n color il',
 'dom house value publishing\r\n color illus',
 ' house value publishing\r\n color illustra',
 'use value publishing\r\n color illustratio',
 ' value publishing\r\n color illustrations ',
 'lue publishing\r\n color illustrations by ',
 ' publishing\r\n color illustrations by mil',
 'blishing\r\n color illustrations by milo w',
 'shing\r\n color illustrations by milo wint',
 'ng\r\n color illustrations by milo winter ',
 '\n color illustrations by milo winter cop',
 'olor illustrations by milo winter copyri',
 'r illustrations by milo winter copyright',
 'llustrations by milo winter copyright  1',
 'strations by milo winter copyright  1915',
 'ations by milo winter copyright  1915, 1',
 'ons by milo winter copyright  1915, 1943',
 ' by milo winter copyright  1915, 1943 by',
 ' milo winter copyright  1915, 1943 by ra',
 'lo winter copyright  1915, 1943 by rand\r',
 'winter copyright  1915, 1943 by rand\r\n m',
 'ter copyright  1915, 1943 by rand\r\n mcna',
 ' copyright  1915, 1943 by rand\r\n mcnally',
 'pyright  1915, 1943 by rand\r\n mcnally & ',
 'ight  1915, 1943 by rand\r\n mcnally & com',
 't  1915, 1943 by rand\r\n mcnally & compan',
 '1915, 1943 by rand\r\n mcnally & company\r\n',
 '5, 1943 by rand\r\n mcnally & company\r\n al',
 '1943 by rand\r\n mcnally & company\r\n all r',
 '3 by rand\r\n mcnally & company\r\n all righ',
 'y rand\r\n mcnally & company\r\n all rights ',
 'and\r\n mcnally & company\r\n all rights res',
 '\r\n mcnally & company\r\n all rights reserv',
 'mcnally & company\r\n all rights reserved.',
 'ally & company\r\n all rights reserved.\r\n\r',
 'y & company\r\n all rights reserved.\r\n\r\n t',
 ' company\r\n all rights reserved.\r\n\r\n this',
 'mpany\r\n all rights reserved.\r\n\r\n this 20',
 'ny\r\n all rights reserved.\r\n\r\n this 2002 ',
 '\n all rights reserved.\r\n\r\n this 2002 edi',
 'll rights reserved.\r\n\r\n this 2002 editio',
 'rights reserved.\r\n\r\n this 2002 edition p',
 'hts reserved.\r\n\r\n this 2002 edition publ',
 ' reserved.\r\n\r\n this 2002 edition publish',
 'served.\r\n\r\n this 2002 edition published ',
 'ved.\r\n\r\n this 2002 edition published by ',
 '.\r\n\r\n this 2002 edition published by gra',
 '\r\n this 2002 edition published by gramer',
 'this 2002 edition published by gramercy ',
 's 2002 edition published by gramercy boo',
 '002 edition published by gramercy books,',
 ' edition published by gramercy books, an',
 'ition published by gramercy books, an im',
 'on published by gramercy books, an impri',
 'published by gramercy books, an imprint ',
 'lished by gramercy books, an imprint of ',
 'hed by gramercy books, an imprint of ran',
 ' by gramercy books, an imprint of random',
 ' gramercy books, an imprint of random\r\n ',
 'amercy books, an imprint of random\r\n hou',
 'rcy books, an imprint of random\r\n house ',
 ' books, an imprint of random\r\n house val',
 'oks, an imprint of random\r\n house value ',
 ', an imprint of random\r\n house value pub',
 'n imprint of random\r\n house value publis',
 'mprint of random\r\n house value publishin',
 'int of random\r\n house value publishing, ',
 ' of random\r\n house value publishing, a d',
 ' random\r\n house value publishing, a divi',
 'ndom\r\n house value publishing, a divisio',
 'm\r\n house value publishing, a division o',
 ' house value publishing, a division of r',
 'use value publishing, a division of rand',
 ' value publishing, a division of random ',
 'lue publishing, a division of random hou',
 ' publishing, a division of random house,',
 'blishing, a division of random house, in',
 'shing, a division of random house, inc.,',
 'ng, a division of random house, inc., 28',
 ' a division of random house, inc., 280 p',
 'division of random house, inc., 280 park',
 'ision of random house, inc., 280 park\r\n ',
 'on of random house, inc., 280 park\r\n ave',
 'of random house, inc., 280 park\r\n avenue',
 'random house, inc., 280 park\r\n avenue, n',
 'dom house, inc., 280 park\r\n avenue, new ',
 ' house, inc., 280 park\r\n avenue, new yor',
 'use, inc., 280 park\r\n avenue, new york, ',
 ', inc., 280 park\r\n avenue, new york, ny ',
 'nc., 280 park\r\n avenue, new york, ny 100',
 ', 280 park\r\n avenue, new york, ny 10017.',
 '80 park\r\n avenue, new york, ny 10017.\r\n\r',
 'park\r\n avenue, new york, ny 10017.\r\n\r\n g',
 'k\r\n avenue, new york, ny 10017.\r\n\r\n gram',
 ' avenue, new york, ny 10017.\r\n\r\n gramerc',
 'enue, new york, ny 10017.\r\n\r\n gramercy i',
 'e, new york, ny 10017.\r\n\r\n gramercy is a',
 'new york, ny 10017.\r\n\r\n gramercy is a re',
 ' york, ny 10017.\r\n\r\n gramercy is a regis',
 'rk, ny 10017.\r\n\r\n gramercy is a register',
 ' ny 10017.\r\n\r\n gramercy is a registered ',
 ' 10017.\r\n\r\n gramercy is a registered tra',
 '017.\r\n\r\n gramercy is a registered tradem',
 '.\r\n\r\n gramercy is a registered trademark',
 '\r\n gramercy is a registered trademark an',
 'gramercy is a registered trademark and t',
 'mercy is a registered trademark and the ',
 'cy is a registered trademark and the col',
 'is a registered trademark and the coloph',
 'a registered trademark and the colophon ',
 'egistered trademark and the colophon is ',
 'stered trademark and the colophon is a t',
 'red trademark and the colophon is a trad',
 ' trademark and the colophon is a tradema',
 'ademark and the colophon is a trademark ',
 'mark and the colophon is a trademark of\r',
 'k and the colophon is a trademark of\r\n r',
 'nd the colophon is a trademark of\r\n rand',
 'the colophon is a trademark of\r\n random ',
 ' colophon is a trademark of\r\n random hou',
 'lophon is a trademark of\r\n random house,',
 'hon is a trademark of\r\n random house, in',
 ' is a trademark of\r\n random house, inc.\r',
 ' a trademark of\r\n random house, inc.\r\n\r\n',
 'trademark of\r\n random house, inc.\r\n\r\n pr',
 'demark of\r\n random house, inc.\r\n\r\n print',
 'ark of\r\n random house, inc.\r\n\r\n printed ',
 ' of\r\n random house, inc.\r\n\r\n printed and',
 '\r\n random house, inc.\r\n\r\n printed and bo',
 'random house, inc.\r\n\r\n printed and bound',
 'dom house, inc.\r\n\r\n printed and bound in',
 ' house, inc.\r\n\r\n printed and bound in th',
 'use, inc.\r\n\r\n printed and bound in the u',
 ', inc.\r\n\r\n printed and bound in the unit',
 'nc.\r\n\r\n printed and bound in the united ',
 '\r\n\r\n printed and bound in the united sta',
 '\n printed and bound in the united states',
 'rinted and bound in the united states of',
 'ted and bound in the united states of am',
 ' and bound in the united states of ameri',
 'd bound in the united states of america\r',
 'ound in the united states of america\r\n\r\n',
 'd in the united states of america\r\n\r\n co',
 'n the united states of america\r\n\r\n cover',
 'he united states of america\r\n\r\n cover de',
 'united states of america\r\n\r\n cover desig',
 'ted states of america\r\n\r\n cover design b',
 ' states of america\r\n\r\n cover design by j',
 'ates of america\r\n\r\n cover design by judy',
 's of america\r\n\r\n cover design by judy fu',
 'f america\r\n\r\n cover design by judy fucci',
 'merica\r\n\r\n cover design by judy fucci, s',
 'ica\r\n\r\n cover design by judy fucci, stud',
 '\r\n\r\n cover design by judy fucci, studio ',
 '\n cover design by judy fucci, studio gra',
 'over design by judy fucci, studio graphi',
 'r design by judy fucci, studio graphix, ',
 'esign by judy fucci, studio graphix, inc',
 'gn by judy fucci, studio graphix, inc.\r\n',
 'by judy fucci, studio graphix, inc.\r\n\r\n ',
 'judy fucci, studio graphix, inc.\r\n\r\n ran',
 'y fucci, studio graphix, inc.\r\n\r\n random',
 'ucci, studio graphix, inc.\r\n\r\n random ho',
 'i, studio graphix, inc.\r\n\r\n random house',
 'studio graphix, inc.\r\n\r\n random house\r\n ',
 'dio graphix, inc.\r\n\r\n random house\r\n new',
 ' graphix, inc.\r\n\r\n random house\r\n new yo',
 'aphix, inc.\r\n\r\n random house\r\n new york ',
 'ix, inc.\r\n\r\n random house\r\n new york  to',
 ' inc.\r\n\r\n random house\r\n new york  toron',
 'c.\r\n\r\n random house\r\n new york  toronto ',
 '\n\r\n random house\r\n new york  toronto  lo',
 ' random house\r\n new york  toronto  londo',
 'ndom house\r\n new york  toronto  london  ',
 'm house\r\n new york  toronto  london  syd',
 'ouse\r\n new york  toronto  london  sydney',
 'e\r\n new york  toronto  london  sydney  a',
 ' new york  toronto  london  sydney  auck',
 'w york  toronto  london  sydney  aucklan',
 'ork  toronto  london  sydney  auckland\r\n',
 '  toronto  london  sydney  auckland\r\n ww',
 'oronto  london  sydney  auckland\r\n www.r',
 'nto  london  sydney  auckland\r\n www.rand',
 '  london  sydney  auckland\r\n www.randomh',
 'ondon  sydney  auckland\r\n www.randomhous',
 'on  sydney  auckland\r\n www.randomhouse.c',
 ' sydney  auckland\r\n www.randomhouse.com\r',
 'dney  auckland\r\n www.randomhouse.com\r\n\r\n',
 'y  auckland\r\n www.randomhouse.com\r\n\r\n\r\n ',
 'auckland\r\n www.randomhouse.com\r\n\r\n\r\n lib',
 'kland\r\n www.randomhouse.com\r\n\r\n\r\n librar',
 'nd\r\n www.randomhouse.com\r\n\r\n\r\n library o',
 '\n www.randomhouse.com\r\n\r\n\r\n library of c',
 'ww.randomhouse.com\r\n\r\n\r\n library of cong',
 'randomhouse.com\r\n\r\n\r\n library of congres',
 'domhouse.com\r\n\r\n\r\n library of congress c',
 'house.com\r\n\r\n\r\n library of congress cata',
 'se.com\r\n\r\n\r\n library of congress catalog',
 'com\r\n\r\n\r\n library of congress cataloging',
 '\r\n\r\n\r\n library of congress cataloging-in',
 '\n\r\n library of congress cataloging-in-pu',
 ' library of congress cataloging-in-publi',
 'brary of congress cataloging-in-publicat',
 'ry of congress cataloging-in-publication',
 'of congress cataloging-in-publication da',
 'congress cataloging-in-publication data\r',
 'gress cataloging-in-publication data\r\n\r\n',
 'ss cataloging-in-publication data\r\n\r\n st',
 'cataloging-in-publication data\r\n\r\n steve',
 'aloging-in-publication data\r\n\r\n stevenso',
 'ging-in-publication data\r\n\r\n stevenson, ',
 'g-in-publication data\r\n\r\n stevenson, rob',
 'n-publication data\r\n\r\n stevenson, robert',
 'ublication data\r\n\r\n stevenson, robert lo',
 'ication data\r\n\r\n stevenson, robert louis',
 'tion data\r\n\r\n stevenson, robert louis, 1',
 'n data\r\n\r\n stevenson, robert louis, 1850',
 'ata\r\n\r\n stevenson, robert louis, 1850-18',
 '\r\n\r\n stevenson, robert louis, 1850-1894.',
 '\n stevenson, robert louis, 1850-1894.\r\n ',
 'tevenson, robert louis, 1850-1894.\r\n    ',
 'enson, robert louis, 1850-1894.\r\n     tr',
 'on, robert louis, 1850-1894.\r\n     treas',
 ' robert louis, 1850-1894.\r\n     treasure',
 'bert louis, 1850-1894.\r\n     treasure is',
 't louis, 1850-1894.\r\n     treasure islan',
 'ouis, 1850-1894.\r\n     treasure island/r',
 's, 1850-1894.\r\n     treasure island/robe',
 '1850-1894.\r\n     treasure island/robert ',
 '0-1894.\r\n     treasure island/robert lou',
 '894.\r\n     treasure island/robert louis ',
 '.\r\n     treasure island/robert louis ste',
 '     treasure island/robert louis steven',
 '  treasure island/robert louis stevenson',
 'reasure island/robert louis stevenson; i',
 'sure island/robert louis stevenson; illu',
 'e island/robert louis stevenson; illustr',
 'sland/robert louis stevenson; illustrate',
 'nd/robert louis stevenson; illustrated i',
 'robert louis stevenson; illustrated in c',
 'ert louis stevenson; illustrated in colo',
 ' louis stevenson; illustrated in color b',
 'uis stevenson; illustrated in color by\r\n',
 ' stevenson; illustrated in color by\r\n   ',
 'evenson; illustrated in color by\r\n   mil',
 'nson; illustrated in color by\r\n   milo w',
 'n; illustrated in color by\r\n   milo wint',
 'illustrated in color by\r\n   milo winter.',
 'ustrated in color by\r\n   milo winter.\r\n ',
 'rated in color by\r\n   milo winter.\r\n    ',
 'ed in color by\r\n   milo winter.\r\n       ',
 'in color by\r\n   milo winter.\r\n       p. ',
 'color by\r\n   milo winter.\r\n       p. cm.',
 'or by\r\n   milo winter.\r\n       p. cm.--(',
 'by\r\n   milo winter.\r\n       p. cm.--(ill',
 '\n   milo winter.\r\n       p. cm.--(illust',
 ' milo winter.\r\n       p. cm.--(illustrat',
 'lo winter.\r\n       p. cm.--(illustrated ',
 'winter.\r\n       p. cm.--(illustrated chi',
 'ter.\r\n       p. cm.--(illustrated childr',
 ".\r\n       p. cm.--(illustrated children'",
 "       p. cm.--(illustrated children's l",
 "    p. cm.--(illustrated children's libr",
 " p. cm.--(illustrated children's library",
 " cm.--(illustrated children's library)\r\n",
 ".--(illustrated children's library)\r\n   ",
 "(illustrated children's library)\r\n     o",
 "lustrated children's library)\r\n     orig",
 "trated children's library)\r\n     origina",
 "ted children's library)\r\n     originally",
 " children's library)\r\n     originally pu",
 "ildren's library)\r\n     originally publi",
 "ren's library)\r\n     originally publishe",
 "'s library)\r\n     originally published: ",
 'library)\r\n     originally published: new',
 'rary)\r\n     originally published: new yo',
 'y)\r\n     originally published: new york:',
 '\n     originally published: new york: ch',
 '   originally published: new york: child',
 'originally published: new york: children',
 "ginally published: new york: children's ",
 "ally published: new york: children's cla",
 "y published: new york: children's classi",
 "ublished: new york: children's classics,",
 "ished: new york: children's classics, 19",
 "ed: new york: children's classics, 1986.",
 " new york: children's classics, 1986.\r\n ",
 "w york: children's classics, 1986.\r\n    ",
 "ork: children's classics, 1986.\r\n     su",
 ": children's classics, 1986.\r\n     summa",
 "hildren's classics, 1986.\r\n     summary:",
 "dren's classics, 1986.\r\n     summary: wh",
 "n's classics, 1986.\r\n     summary: while",
 ' classics, 1986.\r\n     summary: while go',
 'assics, 1986.\r\n     summary: while going',
 'ics, 1986.\r\n     summary: while going th',
 ', 1986.\r\n     summary: while going throu',
 '986.\r\n     summary: while going through ',
 '.\r\n     summary: while going through the',
 '     summary: while going through the po',
 '  summary: while going through the posse',
 'ummary: while going through the possessi',
 'ary: while going through the possessions',
 ': while going through the possessions of',
 'hile going through the possessions of a ',
 'e going through the possessions of a dec',
 'oing through the possessions of a deceas',
 'g through the possessions of a deceased ',
 'hrough the possessions of a deceased gue',
 'ugh the possessions of a deceased guest\r',
 ' the possessions of a deceased guest\r\n  ',
 'e possessions of a deceased guest\r\n   wh',
 'ossessions of a deceased guest\r\n   who o',
 'essions of a deceased guest\r\n   who owed',
 'ions of a deceased guest\r\n   who owed th',
 's of a deceased guest\r\n   who owed them ',
 'f a deceased guest\r\n   who owed them mon',
 ' deceased guest\r\n   who owed them money,',
 'ceased guest\r\n   who owed them money, th',
 'sed guest\r\n   who owed them money, the m',
 ' guest\r\n   who owed them money, the mist',
 'est\r\n   who owed them money, the mistres',
 '\r\n   who owed them money, the mistress o',
 '  who owed them money, the mistress of t',
 'ho owed them money, the mistress of the ',
 'owed them money, the mistress of the inn',
 'd them money, the mistress of the inn an',
 'hem money, the mistress of the inn and h',
 ' money, the mistress of the inn and her ',
 'ney, the mistress of the inn and her son',
 ', the mistress of the inn and her son fi',
 'he mistress of the inn and her son find ',
 'mistress of the inn and her son find a\r\n',
 'tress of the inn and her son find a\r\n   ',
 'ss of the inn and her son find a\r\n   tre',
 'of the inn and her son find a\r\n   treasu',
 'the inn and her son find a\r\n   treasure ',
 ' inn and her son find a\r\n   treasure map',
 'n and her son find a\r\n   treasure map th',
 'nd her son find a\r\n   treasure map that ',
 'her son find a\r\n   treasure map that lea',
 ' son find a\r\n   treasure map that leads ',
 'n find a\r\n   treasure map that leads the',
 'ind a\r\n   treasure map that leads them t',
 ' a\r\n   treasure map that leads them to a',
 '\n   treasure map that leads them to a pi',
 ' treasure map that leads them to a pirat',
 "easure map that leads them to a pirate's",
 "ure map that leads them to a pirate's fo",
 " map that leads them to a pirate's fortu",
 "p that leads them to a pirate's fortune.",
 "hat leads them to a pirate's fortune.\r\n ",
 " leads them to a pirate's fortune.\r\n    ",
 "ads them to a pirate's fortune.\r\n     is",
 " them to a pirate's fortune.\r\n     isbn ",
 "em to a pirate's fortune.\r\n     isbn 0-5",
 "to a pirate's fortune.\r\n     isbn 0-517-",
 "a pirate's fortune.\r\n     isbn 0-517-221",
 "irate's fortune.\r\n     isbn 0-517-22114-",
 "te's fortune.\r\n     isbn 0-517-22114-4\r\n",
 's fortune.\r\n     isbn 0-517-22114-4\r\n   ',
 'ortune.\r\n     isbn 0-517-22114-4\r\n     [',
 'une.\r\n     isbn 0-517-22114-4\r\n     [1. ',
 '.\r\n     isbn 0-517-22114-4\r\n     [1. bur',
 '     isbn 0-517-22114-4\r\n     [1. buried',
 '  isbn 0-517-22114-4\r\n     [1. buried tr',
 'sbn 0-517-22114-4\r\n     [1. buried treas',
 ' 0-517-22114-4\r\n     [1. buried treasure',
 '517-22114-4\r\n     [1. buried treasure--f',
 '-22114-4\r\n     [1. buried treasure--fict',
 '114-4\r\n     [1. buried treasure--fiction',
 '-4\r\n     [1. buried treasure--fiction. 2',
 '\n     [1. buried treasure--fiction. 2. p',
 '   [1. buried treasure--fiction. 2. pira',
 '[1. buried treasure--fiction. 2. pirates',
 ' buried treasure--fiction. 2. pirates--f',
 'ried treasure--fiction. 2. pirates--fict',
 'd treasure--fiction. 2. pirates--fiction',
 'reasure--fiction. 2. pirates--fiction. 3',
 'sure--fiction. 2. pirates--fiction. 3. a',
 'e--fiction. 2. pirates--fiction. 3. adve',
 'fiction. 2. pirates--fiction. 3. adventu',
 'tion. 2. pirates--fiction. 3. adventure\r',
 'n. 2. pirates--fiction. 3. adventure\r\n  ',
 '2. pirates--fiction. 3. adventure\r\n   an',
 'pirates--fiction. 3. adventure\r\n   and a',
 'ates--fiction. 3. adventure\r\n   and adve',
 's--fiction. 3. adventure\r\n   and adventu',
 'fiction. 3. adventure\r\n   and adventures',
 'tion. 3. adventure\r\n   and adventures--f',
 'n. 3. adventure\r\n   and adventures--fict',
 '3. adventure\r\n   and adventures--fiction',
 'adventure\r\n   and adventures--fiction. 4',
 'enture\r\n   and adventures--fiction. 4. c',
 'ure\r\n   and adventures--fiction. 4. cari',
 '\r\n   and adventures--fiction. 4. caribbe',
 '  and adventures--fiction. 4. caribbean ',
 'nd adventures--fiction. 4. caribbean are',
 'adventures--fiction. 4. caribbean area--',
 'entures--fiction. 4. caribbean area--his',
 'ures--fiction. 4. caribbean area--histor',
 's--fiction. 4. caribbean area--history--',
 'fiction. 4. caribbean area--history--18t',
 'tion. 4. caribbean area--history--18th\r\n',
 'n. 4. caribbean area--history--18th\r\n   ',
 '4. caribbean area--history--18th\r\n   cen',
 'caribbean area--history--18th\r\n   centur',
 'ibbean area--history--18th\r\n   century--',
 'ean area--history--18th\r\n   century--fic',
 ' area--history--18th\r\n   century--fictio',
 'ea--history--18th\r\n   century--fiction.]',
 '-history--18th\r\n   century--fiction.] i.',
 'story--18th\r\n   century--fiction.] i. wi',
 'ry--18th\r\n   century--fiction.] i. winte',
 '-18th\r\n   century--fiction.] i. winter, ',
 'th\r\n   century--fiction.] i. winter, mil',
 '\n   century--fiction.] i. winter, milo, ',
 ' century--fiction.] i. winter, milo, 188',
 'ntury--fiction.] i. winter, milo, 1888-1',
 'ry--fiction.] i. winter, milo, 1888-1956',
 '-fiction.] i. winter, milo, 1888-1956, i',
 'ction.] i. winter, milo, 1888-1956, ill.',
 'on.] i. winter, milo, 1888-1956, ill. ii',
 '] i. winter, milo, 1888-1956, ill. ii. t',
 '. winter, milo, 1888-1956, ill. ii. titl',
 'inter, milo, 1888-1956, ill. ii. title.\r',
 'er, milo, 1888-1956, ill. ii. title.\r\n  ',
 ' milo, 1888-1956, ill. ii. title.\r\n   ii',
 'lo, 1888-1956, ill. ii. title.\r\n   iii. ',
 ' 1888-1956, ill. ii. title.\r\n   iii. ser',
 '88-1956, ill. ii. title.\r\n   iii. series',
 '1956, ill. ii. title.\r\n   iii. series.\r\n',
 '6, ill. ii. title.\r\n   iii. series.\r\n\r\n ',
 'ill. ii. title.\r\n   iii. series.\r\n\r\n   p',
 '. ii. title.\r\n   iii. series.\r\n\r\n   pz7.',
 'i. title.\r\n   iii. series.\r\n\r\n   pz7.s84',
 'title.\r\n   iii. series.\r\n\r\n   pz7.s8482 ',
 'le.\r\n   iii. series.\r\n\r\n   pz7.s8482 tr ',
 '\r\n   iii. series.\r\n\r\n   pz7.s8482 tr 200',
 '  iii. series.\r\n\r\n   pz7.s8482 tr 2002\r\n',
 'ii. series.\r\n\r\n   pz7.s8482 tr 2002\r\n   ',
 ' series.\r\n\r\n   pz7.s8482 tr 2002\r\n   [fi',
 'ries.\r\n\r\n   pz7.s8482 tr 2002\r\n   [fic]-',
 's.\r\n\r\n   pz7.s8482 tr 2002\r\n   [fic]--dc',
 '\n\r\n   pz7.s8482 tr 2002\r\n   [fic]--dc21\r',
 '   pz7.s8482 tr 2002\r\n   [fic]--dc21\r\n\r\n',
 'pz7.s8482 tr 2002\r\n   [fic]--dc21\r\n\r\n   ',
 '.s8482 tr 2002\r\n   [fic]--dc21\r\n\r\n      ',
 '482 tr 2002\r\n   [fic]--dc21\r\n\r\n         ',
 ' tr 2002\r\n   [fic]--dc21\r\n\r\n            ',
 ' 2002\r\n   [fic]--dc21\r\n\r\n               ',
 '02\r\n   [fic]--dc21\r\n\r\n                  ',
 '\n   [fic]--dc21\r\n\r\n                     ',
 ' [fic]--dc21\r\n\r\n                        ',
 'ic]--dc21\r\n\r\n                           ',
 '--dc21\r\n\r\n                              ',
 'c21\r\n\r\n                                 ',
 '\r\n\r\n                                    ',
 '\n                                       ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                       2',
 '                                    2002',
 '                                 2002023',
 '                              2002023301',
 '                           2002023301\r\n ',
 '                        2002023301\r\n 9 8',
 '                     2002023301\r\n 9 8 7 ',
 '                  2002023301\r\n 9 8 7 6 5',
 '               2002023301\r\n 9 8 7 6 5 4 ',
 '            2002023301\r\n 9 8 7 6 5 4 3 2',
 '         2002023301\r\n 9 8 7 6 5 4 3 2 1\r',
 '      2002023301\r\n 9 8 7 6 5 4 3 2 1\r\n\r\n',
 '   2002023301\r\n 9 8 7 6 5 4 3 2 1\r\n\r\n\r\nt',
 '2002023301\r\n 9 8 7 6 5 4 3 2 1\r\n\r\n\r\ntran',
 '2023301\r\n 9 8 7 6 5 4 3 2 1\r\n\r\n\r\ntranscr',
 '3301\r\n 9 8 7 6 5 4 3 2 1\r\n\r\n\r\ntranscribe',
 "1\r\n 9 8 7 6 5 4 3 2 1\r\n\r\n\r\ntranscriber's",
 " 9 8 7 6 5 4 3 2 1\r\n\r\n\r\ntranscriber's no",
 "8 7 6 5 4 3 2 1\r\n\r\n\r\ntranscriber's note:",
 " 6 5 4 3 2 1\r\n\r\n\r\ntranscriber's note:\r\n\r",
 "5 4 3 2 1\r\n\r\n\r\ntranscriber's note:\r\n\r\n  ",
 " 3 2 1\r\n\r\n\r\ntranscriber's note:\r\n\r\n    m",
 "2 1\r\n\r\n\r\ntranscriber's note:\r\n\r\n    mino",
 "\r\n\r\n\r\ntranscriber's note:\r\n\r\n    minor s",
 "\n\r\ntranscriber's note:\r\n\r\n    minor spel",
 "transcriber's note:\r\n\r\n    minor spellin",
 "nscriber's note:\r\n\r\n    minor spelling a",
 "riber's note:\r\n\r\n    minor spelling and ",
 "er's note:\r\n\r\n    minor spelling and typ",
 's note:\r\n\r\n    minor spelling and typogr',
 'ote:\r\n\r\n    minor spelling and typograph',
 ':\r\n\r\n    minor spelling and typographica',
 '\r\n    minor spelling and typographical e',
 '   minor spelling and typographical erro',
 'minor spelling and typographical errors ',
 'or spelling and typographical errors hav',
 'spelling and typographical errors have b',
 'lling and typographical errors have been',
 'ng and typographical errors have been co',
 'and typographical errors have been corre',
 ' typographical errors have been correcte',
 'pographical errors have been corrected w',
 'raphical errors have been corrected with',
 'hical errors have been corrected without',
 'al errors have been corrected without\r\n ',
 'errors have been corrected without\r\n    ',
 'ors have been corrected without\r\n    not',
 ' have been corrected without\r\n    note. ',
 've been corrected without\r\n    note. dia',
 'been corrected without\r\n    note. dialec',
 'n corrected without\r\n    note. dialect a',
 'orrected without\r\n    note. dialect and ',
 'ected without\r\n    note. dialect and var',
 'ed without\r\n    note. dialect and varian',
 'without\r\n    note. dialect and variant s',
 'hout\r\n    note. dialect and variant spel',
 't\r\n    note. dialect and variant spellin',
 '    note. dialect and variant spellings ',
 ' note. dialect and variant spellings hav',
 'te. dialect and variant spellings have b',
 ' dialect and variant spellings have been',
 'alect and variant spellings have been re',
 'ct and variant spellings have been retai',
 'and variant spellings have been retained',
 ' variant spellings have been retained, w',
 'riant spellings have been retained, whil',
 'nt spellings have been retained, whilst\r',
 'spellings have been retained, whilst\r\n  ',
 'llings have been retained, whilst\r\n    i',
 'ngs have been retained, whilst\r\n    inco',
 ' have been retained, whilst\r\n    inconsi',
 've been retained, whilst\r\n    inconsiste',
 'been retained, whilst\r\n    inconsistent ',
 'n retained, whilst\r\n    inconsistent hyp',
 'etained, whilst\r\n    inconsistent hyphen',
 'ined, whilst\r\n    inconsistent hyphenati',
 'd, whilst\r\n    inconsistent hyphenation ',
 'whilst\r\n    inconsistent hyphenation has',
 'lst\r\n    inconsistent hyphenation has be',
 '\r\n    inconsistent hyphenation has been ',
 '   inconsistent hyphenation has been sta',
 'inconsistent hyphenation has been standa',
 'onsistent hyphenation has been standardi',
 'istent hyphenation has been standardised',
 'ent hyphenation has been standardised. c',
 ' hyphenation has been standardised. colo',
 'phenation has been standardised. color p',
 'nation has been standardised. color plat',
 'ion has been standardised. color plates ',
 ' has been standardised. color plates hav',
 's been standardised. color plates have\r\n',
 'een standardised. color plates have\r\n   ',
 ' standardised. color plates have\r\n    be',
 'andardised. color plates have\r\n    been ',
 'ardised. color plates have\r\n    been rep',
 'ised. color plates have\r\n    been reposi',
 'd. color plates have\r\n    been repositio',
 'color plates have\r\n    been repositioned',
 'or plates have\r\n    been repositioned ac',
 'plates have\r\n    been repositioned accor',
 'tes have\r\n    been repositioned accordin',
 ' have\r\n    been repositioned according t',
 've\r\n    been repositioned according to t',
 '\n    been repositioned according to thei',
 '  been repositioned according to their c',
 'een repositioned according to their capt',
 ' repositioned according to their caption',
 'positioned according to their captions; ',
 'itioned according to their captions; the',
 "oned according to their captions; the 'c",
 "d according to their captions; the 'colo",
 "ccording to their captions; the 'color p",
 "rding to their captions; the 'color plat",
 "ng to their captions; the 'color plates'",
 "to their captions; the 'color plates'\r\n ",
 "their captions; the 'color plates'\r\n    ",
 "ir captions; the 'color plates'\r\n    lis",
 "captions; the 'color plates'\r\n    listin",
 "tions; the 'color plates'\r\n    listing r",
 "ns; the 'color plates'\r\n    listing rema",
 " the 'color plates'\r\n    listing remains",
 "e 'color plates'\r\n    listing remains as",
 "color plates'\r\n    listing remains as pr",
 "or plates'\r\n    listing remains as print",
 "plates'\r\n    listing remains as printed ",
 "tes'\r\n    listing remains as printed to ",
 "'\r\n    listing remains as printed to ind",
 '    listing remains as printed to indica',
 ' listing remains as printed to indicate ',
 'sting remains as printed to indicate the',
 'ng remains as printed to indicate the or',
 'remains as printed to indicate the origi',
 'ains as printed to indicate the original',
 's as printed to indicate the original lo',
 's printed to indicate the original locat',
 'rinted to indicate the original location',
 'ted to indicate the original locations.\r',
 ' to indicate the original locations.\r\n\r\n',
 ' indicate the original locations.\r\n\r\n\r\n\r',
 'dicate the original locations.\r\n\r\n\r\n\r\n\r\n',
 'ate the original locations.\r\n\r\n\r\n\r\n\r\ncon',
 ' the original locations.\r\n\r\n\r\n\r\n\r\nconten',
 'e original locations.\r\n\r\n\r\n\r\n\r\ncontents\r',
 'riginal locations.\r\n\r\n\r\n\r\n\r\ncontents\r\n\r\n',
 'inal locations.\r\n\r\n\r\n\r\n\r\ncontents\r\n\r\n\r\n ',
 'l locations.\r\n\r\n\r\n\r\n\r\ncontents\r\n\r\n\r\n    ',
 'ocations.\r\n\r\n\r\n\r\n\r\ncontents\r\n\r\n\r\n       ',
 'tions.\r\n\r\n\r\n\r\n\r\ncontents\r\n\r\n\r\n          ',
 'ns.\r\n\r\n\r\n\r\n\r\ncontents\r\n\r\n\r\n             ',
 '\r\n\r\n\r\n\r\n\r\ncontents\r\n\r\n\r\n                ',
 '\n\r\n\r\n\r\ncontents\r\n\r\n\r\n                   ',
 '\r\n\r\ncontents\r\n\r\n\r\n                      ',
 '\ncontents\r\n\r\n\r\n                         ',
 'ntents\r\n\r\n\r\n                            ',
 'nts\r\n\r\n\r\n                               ',
 '\r\n\r\n\r\n                                  ',
 '\n\r\n                                     ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                        ',
 '                                     pag',
 '                                  page\r\n',
 '                               page\r\n _t',
 '                            page\r\n _to t',
 '                         page\r\n _to the ',
 '                      page\r\n _to the hes',
 '                   page\r\n _to the hesita',
 '                page\r\n _to the hesitatin',
 '             page\r\n _to the hesitating p',
 '          page\r\n _to the hesitating purc',
 '       page\r\n _to the hesitating purchas',
 '    page\r\n _to the hesitating purchaser_',
 ' page\r\n _to the hesitating purchaser_   ',
 'ge\r\n _to the hesitating purchaser_      ',
 '\n _to the hesitating purchaser_         ',
 'to the hesitating purchaser_            ',
 'the hesitating purchaser_               ',
 ' hesitating purchaser_                  ',
 'sitating purchaser_                     ',
 'ating purchaser_                        ',
 'ng purchaser_                           ',
 'purchaser_                             _',
 'chaser_                             _vii',
 'ser_                             _viii_\r',
 '_                             _viii_\r\n _',
 '                           _viii_\r\n _lis',
 '                        _viii_\r\n _list o',
 '                     _viii_\r\n _list of c',
 '                  _viii_\r\n _list of colo',
 '               _viii_\r\n _list of color p',
 '            _viii_\r\n _list of color plat',
 '         _viii_\r\n _list of color plates_',
 '      _viii_\r\n _list of color plates_   ',
 '   _viii_\r\n _list of color plates_      ',
 '_viii_\r\n _list of color plates_         ',
 'ii_\r\n _list of color plates_            ',
 '\r\n _list of color plates_               ',
 '_list of color plates_                  ',
 'st of color plates_                     ',
 'of color plates_                        ',
 'color plates_                           ',
 'or plates_                              ',
 ...]
print('Vectorization...')
x = np.zeros((len(sentences), maxlen, len(chars)), dtype=np.bool)
y = np.zeros((len(sentences), len(chars)), dtype=np.bool)
for i, sentence in enumerate(sentences):
    for t, char in enumerate(sentence):
        x[i, t, char_indices[char]] = 1
    y[i, char_indices[next_chars[i]]] = 1
Vectorization...
x.shape
(132454, 40, 60)
y.shape
(132454, 60)
The dummy variables for  are shown below.

y[0:10]
array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False, False]])
Next, we create the neural network. This neural network's primary feature is the LSTM layer, which allows the sequences to be processed.

# build the model: a single LSTM
print('Build model...')
model = Sequential()
model.add(LSTM(128, input_shape=(maxlen, len(chars))))
model.add(Dense(len(chars), activation='softmax'))

optimizer = RMSprop(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=optimizer)
Build model...
model.summary()
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm (LSTM)                  (None, 128)               96768     
_________________________________________________________________
dense (Dense)                (None, 60)                7740      
=================================================================
Total params: 104,508
Trainable params: 104,508
Non-trainable params: 0
_________________________________________________________________
The LSTM will produce new text character by character. We will need to sample the correct letter from the LSTM predictions each time. The sample function accepts the following two parameters:

preds - The output neurons.
temperature - 1.0 is the most conservative, 0.0 is the most confident (willing to make spelling and other errors).
The sample function below is essentially performing a softmax on the neural network predictions. This causes each output neuron to become a probability of its particular letter.

def sample(preds, temperature=1.0):
    # helper function to sample an index from a probability array
    preds = np.asarray(preds).astype('float64')
    preds = np.log(preds) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)
Keras calls the following function at the end of each training Epoch. The code generates sample text generations that visually demonstrate the neural network better at text generation. As the neural network trains, the generations should look more realistic.

def on_epoch_end(epoch, _):
    # Function invoked at end of each epoch. Prints generated text.
    print("******************************************************")
    print('----- Generating text after Epoch: %d' % epoch)

    start_index = random.randint(0, len(processed_text) - maxlen - 1)
    for temperature in [0.2, 0.5, 1.0, 1.2]:
        print('----- temperature:', temperature)

        generated = ''
        sentence = processed_text[start_index: start_index + maxlen]
        generated += sentence
        print('----- Generating with seed: "' + sentence + '"')
        sys.stdout.write(generated)

        for i in range(400):
            x_pred = np.zeros((1, maxlen, len(chars)))
            for t, char in enumerate(sentence):
                x_pred[0, t, char_indices[char]] = 1.

            preds = model.predict(x_pred, verbose=0)[0]
            next_index = sample(preds, temperature)
            next_char = indices_char[next_index]

            generated += next_char
            sentence = sentence[1:] + next_char

            sys.stdout.write(next_char)
            sys.stdout.flush()
        print()
We are now ready to train. It can take up to an hour to train this network, depending on how fast your computer is. If you have a GPU available, please make sure to use it.

# Ignore useless W0819 warnings generated by TensorFlow 2.0.  Hopefully can remove this ignore in the future.
# See https://github.com/tensorflow/tensorflow/issues/31308
import logging, os
logging.disable(logging.WARNING)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

# Fit the model
print_callback = LambdaCallback(on_epoch_end=on_epoch_end)

model.fit(x, y,
          batch_size=128,
          epochs=60,
          callbacks=[print_callback])
Train on 132454 samples
Epoch 1/60
   128/132454 [..............................] - ETA: 35:39******************************************************
----- Generating text after Epoch: 0
----- temperature: 0.2
----- Generating with seed: "im shouting.

but you may suppose i pa"
im shouting.

but you may suppose i pa
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-16-29d39d1d557e> in <module>
     11           batch_size=128,
     12           epochs=60,
---> 13           callbacks=[print_callback])

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    395                       total_epochs=1)
    396                   cbks.make_logs(model, epoch_logs, eval_result, ModeKeys.TEST,
--> 397                                  prefix='val_')
    398 
    399     return model.history

~\miniconda3\envs\tensorflow\lib\contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in on_epoch(self, epoch, mode)
    769       if mode == ModeKeys.TRAIN:
    770         # Epochs only apply to `fit`.
--> 771         self.callbacks.on_epoch_end(epoch, epoch_logs)
    772       self.progbar.on_epoch_end(epoch, epoch_logs)
    773 

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\callbacks.py in on_epoch_end(self, epoch, logs)
    300     logs = logs or {}
    301     for callback in self.callbacks:
--> 302       callback.on_epoch_end(epoch, logs)
    303 
    304   def on_train_batch_begin(self, batch, logs=None):

<ipython-input-15-6e1e333ca3e9> in on_epoch_end(epoch, _)
     19                 x_pred[0, t, char_indices[char]] = 1.
     20 
---> 21             preds = model.predict(x_pred, verbose=0)[0]
     22             next_index = sample(preds, temperature)
     23             next_char = indices_char[next_index]

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1011         max_queue_size=max_queue_size,
   1012         workers=workers,
-> 1013         use_multiprocessing=use_multiprocessing)
   1014 
   1015   def reset_metrics(self):

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in predict(self, model, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    496         model, ModeKeys.PREDICT, x=x, batch_size=batch_size, verbose=verbose,
    497         steps=steps, callbacks=callbacks, max_queue_size=max_queue_size,
--> 498         workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
    499 
    500 

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in _model_iteration(self, model, mode, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    473               mode=mode,
    474               training_context=training_context,
--> 475               total_epochs=1)
    476           cbks.make_logs(model, epoch_logs, result, mode)
    477 

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    126         step=step, mode=mode, size=current_batch_size) as batch_logs:
    127       try:
--> 128         batch_outs = execution_function(iterator)
    129       except (StopIteration, errors.OutOfRangeError):
    130         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
     96     # `numpy` translates Tensors to values in Eager mode.
     97     return nest.map_structure(_non_none_constant_value,
---> 98                               distributed_function(input_fn))
     99 
    100   return execution_function

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    636               *args, **kwds)
    637       # If we did not create any variables the trace we have is good enough.
--> 638       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    639 
    640     def fn_with_cond(*inner_args, **inner_kwds):

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
   1609          if isinstance(t, (ops.Tensor,
   1610                            resource_variable_ops.BaseResourceVariable))),
-> 1611         self.captured_inputs)
   1612 
   1613   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

~\miniconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~\miniconda3\envs\tensorflow\lib\site-packages\six.py in raise_from(value, from_value)

UnknownError:  [_Derived_]  Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential/lstm/StatefulPartitionedCall]] [Op:__inference_distributed_function_3394]

Function call stack:
distributed_function -> distributed_function -> distributed_function
 
